config/routes.rb
Pinteresting::Application.routes.draw do
  devise_for :users
 root "pages#home"
 get "about" => "pages#about"
 get "instructions" => "pages#instructions"
 get "team" => "pages#team"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

   def instructions 
  end


   def Team
  end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "W-9NINE", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
         <li><%= link_to "About W-9NINE", about_path %></li>
         <li><%= link_to "Instructions", instructions_path %></li>
         <li><%= link_to "Our Team", team_path %></li>
          <% if user_signed_in? %>
         <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
         <% else %>
           <li><%= link_to "Sign in", new_user_session_path %></li>
         <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>W-9NINE.com</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>
 <%= yield %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p> "Providing you with a time management tool that enables you to utilize your resources effectively"</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to</h1>
	<h1>W-9NINE!!! </h1>
	<% if user_signed_in? %>
	 Hello, and Welcome Valued Member
	<% else %>
	<p> Members Click Here to  <%= link_to "Sign In", new_user_session_path, class: "btn btn-default btn-lg" %>.</p>
	
	<p> Esteemed Guest Please Click Here to  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-default btn-lg" %>.</p>
	<% end %>

 </div>

app/views/pages/instructions.html.erb
<h1>Instructions to help you properly fill out your sheet.</h1>

app/views/pages/team.html.erb
        <h1> W-9NINE TEAM  </h1>


<h3> Isaiya White, President, CEO, and Co-Founder</h3> <h4>Isaiya wears numerous hats of responsibility, and strives to be a lifelong student, traveler, and seeker of the good in people. </h4>
 
<h3> Patricia White, VP of Human Resources, and Co-Founder </h3>  <h4>Patricia is A true lover of history, and loves to discuss philosophical topics. </h4>

<h3>  Ronnie Howard, VP of Sales and Marketing, and Co-Founder</h3> <h4>Ronnie is a devoted Father of 3 lovely children, and is a lover of all things Basketball!!! </h4>

<h3> Karen Goloskie, Company Controller 
</h3> <h4>Karen is the very definition of Sage, and loves to go on long walks with her dog child. </h4>